import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';

const SOURCE_DIRS = [
  {
    dir: path.resolve('src/assets/Products'),
    outputPrefix: '../assets/Products',
    type: 'asset'
  },
  {
    dir: path.resolve('public/images'),
    outputPrefix: '/images',
    type: 'public'
  }
];

const TARGET_WIDTHS = [400, 800, 1200];
const FORMATS = ['avif', 'webp']; // we'll also output original optimized format

async function getImages(dir, fileList = []) {
  const files = await fs.readdir(dir, { withFileTypes: true });
  for (const file of files) {
    const filePath = path.join(dir, file.name);
    if (file.isDirectory()) {
      if (file.name !== 'optimized') {
        await getImages(filePath, fileList);
      }
    } else {
      const ext = path.extname(file.name).toLowerCase();
      if (['.jpg', '.jpeg', '.png', '.webp'].includes(ext)) {
        fileList.push(filePath);
      }
    }
  }
  return fileList;
}

async function run() {
  const registryEntries = [];

  for (const { dir, outputPrefix, type } of SOURCE_DIRS) {
    try {
      await fs.access(dir);
    } catch {
      console.warn(`Directory not found: ${dir}`);
      continue;
    }

    const images = await getImages(dir);
    console.log(`Found ${images.length} images in ${dir}`);

    for (const imagePath of images) {
      const parentDir = path.dirname(imagePath);
      const optimizedDir = path.join(parentDir, 'optimized');
      await fs.mkdir(optimizedDir, { recursive: true });

      const ext = path.extname(imagePath).toLowerCase();
      const baseName = path.basename(imagePath, ext);
      const meta = await sharp(imagePath).metadata();
      const originalWidth = meta.width || 800;

      const outputs = {
        avif: [],
        webp: [],
        fallback: []
      };

      // Generate optimized images
      for (const width of TARGET_WIDTHS) {
        if (width > originalWidth && width !== TARGET_WIDTHS[0]) {
          continue; // skip widths larger than original unless it's the smallest size
        }

        const resizeWidth = Math.min(width, originalWidth);
        const sizesNameSuffix = `-${resizeWidth}`;

        // 1. Convert to AVIF
        const avifFilename = `${baseName}${sizesNameSuffix}.avif`;
        const avifOutPath = path.join(optimizedDir, avifFilename);
        await sharp(imagePath)
          .resize(resizeWidth)
          .avif({ quality: 65 })
          .toFile(avifOutPath);
        outputs.avif.push({ width: resizeWidth, filename: avifFilename });

        // 2. Convert to WebP
        const webpFilename = `${baseName}${sizesNameSuffix}.webp`;
        const webpOutPath = path.join(optimizedDir, webpFilename);
        await sharp(imagePath)
          .resize(resizeWidth)
          .webp({ quality: 75 })
          .toFile(webpOutPath);
        outputs.webp.push({ width: resizeWidth, filename: webpFilename });

        // 3. Keep original format (optimized)
        const formatFilename = `${baseName}${sizesNameSuffix}${ext}`;
        const formatOutPath = path.join(optimizedDir, formatFilename);
        let sharpObj = sharp(imagePath).resize(resizeWidth);
        if (ext === '.png') {
          sharpObj = sharpObj.png({ quality: 80, compressionLevel: 9 });
        } else {
          sharpObj = sharpObj.jpeg({ quality: 80, progressive: true });
        }
        await sharpObj.toFile(formatOutPath);
        outputs.fallback.push({ width: resizeWidth, filename: formatFilename });
      }

      // Record output metadata relative paths
      const relParentDir = path.relative(path.resolve('src/data'), parentDir).replace(/\\/g, '/');
      const relOriginalPath = path.relative(path.resolve('src/data'), imagePath).replace(/\\/g, '/');
      const relativeOrigPrefix = type === 'public' ? outputPrefix : outputPrefix;

      registryEntries.push({
        type,
        originalName: baseName,
        originalExt: ext,
        originalPath: relOriginalPath, // relative path from registry file to original
        publicOrigPath: `${outputPrefix}/${path.relative(dir, imagePath).replace(/\\/g, '/')}`,
        optimizedDir: `${relParentDir}/optimized`,
        outputs
      });
    }
  }

  // Generate optimized-images.ts contents
  let tsImports = `// This file is auto-generated by scripts/optimize-images.js. Do not edit directly.\n`;
  let tsRegistry = `\nexport interface OptimizedImageSource {\n  avif: string;\n  webp: string;\n  fallback: string;\n}\n\n`;

  // We need to generate static imports for all optimized asset files so Vite bundles them
  let importCounter = 0;
  const assetImports = [];
  const entriesCode = [];

  for (const entry of registryEntries) {
    if (entry.type === 'asset') {
      const baseImportName = `orig_${importCounter++}`;
      tsImports += `import ${baseImportName} from '${entry.originalPath}';\n`;

      const avifImportNames = [];
      const webpImportNames = [];
      const fallbackImportNames = [];

      for (const avif of entry.outputs.avif) {
        const importName = `avif_${importCounter++}`;
        tsImports += `import ${importName} from '${entry.optimizedDir}/${avif.filename}';\n`;
        avifImportNames.push(`${importName} + ' ${avif.width}w'`);
      }

      for (const webp of entry.outputs.webp) {
        const importName = `webp_${importCounter++}`;
        tsImports += `import ${importName} from '${entry.optimizedDir}/${webp.filename}';\n`;
        webpImportNames.push(`${importName} + ' ${webp.width}w'`);
      }

      let fallbackDefault = '';
      for (const fallback of entry.outputs.fallback) {
        const importName = `fb_${importCounter++}`;
        tsImports += `import ${importName} from '${entry.optimizedDir}/${fallback.filename}';\n`;
        fallbackImportNames.push(`${importName} + ' ${fallback.width}w'`);
        // Use the middle size (e.g. 800w) or the largest available as the default fallback
        if (!fallbackDefault || fallback.width === 800) {
          fallbackDefault = importName;
        }
      }

      entriesCode.push(`  [${baseImportName}, {
    avif: [${avifImportNames.join(', ')}].join(', '),
    webp: [${webpImportNames.join(', ')}].join(', '),
    fallback: ${fallbackDefault}
  }]`);
    } else {
      // For public files, we use string paths directly since they are in public/ directory
      const avifSrcset = entry.outputs.avif.map(a => `\`${entry.publicOrigPath.replace(path.basename(entry.publicOrigPath), 'optimized/' + a.filename)} ${a.width}w\``).join(', ');
      const webpSrcset = entry.outputs.webp.map(w => `\`${entry.publicOrigPath.replace(path.basename(entry.publicOrigPath), 'optimized/' + w.filename)} ${w.width}w\``).join(', ');
      
      const fallbackMiddle = entry.outputs.fallback.find(f => f.width === 800) || entry.outputs.fallback[entry.outputs.fallback.length - 1];
      const fallbackPath = entry.publicOrigPath.replace(path.basename(entry.publicOrigPath), 'optimized/' + fallbackMiddle.filename);

      entriesCode.push(`  ['${entry.publicOrigPath}', {
    avif: [${avifSrcset}].join(', '),
    webp: [${webpSrcset}].join(', '),
    fallback: '${fallbackPath}'
  }]`);
    }
  }

  tsRegistry += `export const optimizedImagesMap = new Map<string | any, OptimizedImageSource>([\n${entriesCode.join(',\n')}\n]);\n`;

  const outFilePath = path.resolve('src/data/optimized-images.ts');
  await fs.mkdir(path.dirname(outFilePath), { recursive: true });
  await fs.writeFile(outFilePath, tsImports + tsRegistry, 'utf8');
  console.log(`Successfully generated registry at ${outFilePath}`);
}

run().catch(console.error);
