// This file is auto-generated by scripts/optimize-images.js. Do not edit directly.
import orig_0 from '../assets/Products/Trip-1/T1.jpg';
import avif_1 from '../assets/Products/Trip-1/optimized/T1-400.avif';
import webp_2 from '../assets/Products/Trip-1/optimized/T1-400.webp';
import fb_3 from '../assets/Products/Trip-1/optimized/T1-400.jpg';
import orig_4 from '../assets/Products/Trip-1/T11.jpg';
import avif_5 from '../assets/Products/Trip-1/optimized/T11-400.avif';
import webp_6 from '../assets/Products/Trip-1/optimized/T11-400.webp';
import fb_7 from '../assets/Products/Trip-1/optimized/T11-400.jpg';
import orig_8 from '../assets/Products/Trip-1/T111.jpg';
import avif_9 from '../assets/Products/Trip-1/optimized/T111-400.avif';
import avif_10 from '../assets/Products/Trip-1/optimized/T111-800.avif';
import avif_11 from '../assets/Products/Trip-1/optimized/T111-1200.avif';
import webp_12 from '../assets/Products/Trip-1/optimized/T111-400.webp';
import webp_13 from '../assets/Products/Trip-1/optimized/T111-800.webp';
import webp_14 from '../assets/Products/Trip-1/optimized/T111-1200.webp';
import fb_15 from '../assets/Products/Trip-1/optimized/T111-400.jpg';
import fb_16 from '../assets/Products/Trip-1/optimized/T111-800.jpg';
import fb_17 from '../assets/Products/Trip-1/optimized/T111-1200.jpg';
import orig_18 from '../assets/Products/Trip-1/T1111.webp';
import avif_19 from '../assets/Products/Trip-1/optimized/T1111-400.avif';
import webp_20 from '../assets/Products/Trip-1/optimized/T1111-400.webp';
import fb_21 from '../assets/Products/Trip-1/optimized/T1111-400.webp';
import orig_22 from '../assets/Products/Trip-1/T11111.jpg';
import avif_23 from '../assets/Products/Trip-1/optimized/T11111-400.avif';
import avif_24 from '../assets/Products/Trip-1/optimized/T11111-800.avif';
import webp_25 from '../assets/Products/Trip-1/optimized/T11111-400.webp';
import webp_26 from '../assets/Products/Trip-1/optimized/T11111-800.webp';
import fb_27 from '../assets/Products/Trip-1/optimized/T11111-400.jpg';
import fb_28 from '../assets/Products/Trip-1/optimized/T11111-800.jpg';
import orig_29 from '../assets/Products/Trip-2/T2.jpg';
import avif_30 from '../assets/Products/Trip-2/optimized/T2-400.avif';
import avif_31 from '../assets/Products/Trip-2/optimized/T2-800.avif';
import avif_32 from '../assets/Products/Trip-2/optimized/T2-1200.avif';
import webp_33 from '../assets/Products/Trip-2/optimized/T2-400.webp';
import webp_34 from '../assets/Products/Trip-2/optimized/T2-800.webp';
import webp_35 from '../assets/Products/Trip-2/optimized/T2-1200.webp';
import fb_36 from '../assets/Products/Trip-2/optimized/T2-400.jpg';
import fb_37 from '../assets/Products/Trip-2/optimized/T2-800.jpg';
import fb_38 from '../assets/Products/Trip-2/optimized/T2-1200.jpg';
import orig_39 from '../assets/Products/Trip-2/T22.jpg';
import avif_40 from '../assets/Products/Trip-2/optimized/T22-400.avif';
import avif_41 from '../assets/Products/Trip-2/optimized/T22-800.avif';
import webp_42 from '../assets/Products/Trip-2/optimized/T22-400.webp';
import webp_43 from '../assets/Products/Trip-2/optimized/T22-800.webp';
import fb_44 from '../assets/Products/Trip-2/optimized/T22-400.jpg';
import fb_45 from '../assets/Products/Trip-2/optimized/T22-800.jpg';
import orig_46 from '../assets/Products/Trip-2/T222.jpg';
import avif_47 from '../assets/Products/Trip-2/optimized/T222-400.avif';
import webp_48 from '../assets/Products/Trip-2/optimized/T222-400.webp';
import fb_49 from '../assets/Products/Trip-2/optimized/T222-400.jpg';
import orig_50 from '../assets/Products/Trip-2/T2222.jpg';
import avif_51 from '../assets/Products/Trip-2/optimized/T2222-259.avif';
import webp_52 from '../assets/Products/Trip-2/optimized/T2222-259.webp';
import fb_53 from '../assets/Products/Trip-2/optimized/T2222-259.jpg';
import orig_54 from '../assets/Products/Trip-2/T22222.jpg';
import avif_55 from '../assets/Products/Trip-2/optimized/T22222-400.avif';
import avif_56 from '../assets/Products/Trip-2/optimized/T22222-800.avif';
import avif_57 from '../assets/Products/Trip-2/optimized/T22222-1200.avif';
import webp_58 from '../assets/Products/Trip-2/optimized/T22222-400.webp';
import webp_59 from '../assets/Products/Trip-2/optimized/T22222-800.webp';
import webp_60 from '../assets/Products/Trip-2/optimized/T22222-1200.webp';
import fb_61 from '../assets/Products/Trip-2/optimized/T22222-400.jpg';
import fb_62 from '../assets/Products/Trip-2/optimized/T22222-800.jpg';
import fb_63 from '../assets/Products/Trip-2/optimized/T22222-1200.jpg';
import orig_64 from '../assets/Products/Trip-3/T3.jpg';
import avif_65 from '../assets/Products/Trip-3/optimized/T3-400.avif';
import avif_66 from '../assets/Products/Trip-3/optimized/T3-800.avif';
import avif_67 from '../assets/Products/Trip-3/optimized/T3-1200.avif';
import webp_68 from '../assets/Products/Trip-3/optimized/T3-400.webp';
import webp_69 from '../assets/Products/Trip-3/optimized/T3-800.webp';
import webp_70 from '../assets/Products/Trip-3/optimized/T3-1200.webp';
import fb_71 from '../assets/Products/Trip-3/optimized/T3-400.jpg';
import fb_72 from '../assets/Products/Trip-3/optimized/T3-800.jpg';
import fb_73 from '../assets/Products/Trip-3/optimized/T3-1200.jpg';
import orig_74 from '../assets/Products/Trip-3/T33.webp';
import avif_75 from '../assets/Products/Trip-3/optimized/T33-400.avif';
import avif_76 from '../assets/Products/Trip-3/optimized/T33-800.avif';
import webp_77 from '../assets/Products/Trip-3/optimized/T33-400.webp';
import webp_78 from '../assets/Products/Trip-3/optimized/T33-800.webp';
import fb_79 from '../assets/Products/Trip-3/optimized/T33-400.webp';
import fb_80 from '../assets/Products/Trip-3/optimized/T33-800.webp';
import orig_81 from '../assets/Products/Trip-3/T333.jpg';
import avif_82 from '../assets/Products/Trip-3/optimized/T333-259.avif';
import webp_83 from '../assets/Products/Trip-3/optimized/T333-259.webp';
import fb_84 from '../assets/Products/Trip-3/optimized/T333-259.jpg';
import orig_85 from '../assets/Products/Trip-3/T3333.jpg';
import avif_86 from '../assets/Products/Trip-3/optimized/T3333-225.avif';
import webp_87 from '../assets/Products/Trip-3/optimized/T3333-225.webp';
import fb_88 from '../assets/Products/Trip-3/optimized/T3333-225.jpg';
import orig_89 from '../assets/Products/Trip-3/T33333.jpg';
import avif_90 from '../assets/Products/Trip-3/optimized/T33333-400.avif';
import avif_91 from '../assets/Products/Trip-3/optimized/T33333-800.avif';
import webp_92 from '../assets/Products/Trip-3/optimized/T33333-400.webp';
import webp_93 from '../assets/Products/Trip-3/optimized/T33333-800.webp';
import fb_94 from '../assets/Products/Trip-3/optimized/T33333-400.jpg';
import fb_95 from '../assets/Products/Trip-3/optimized/T33333-800.jpg';
import orig_96 from '../assets/Products/Trip-4/T4.jpg';
import avif_97 from '../assets/Products/Trip-4/optimized/T4-400.avif';
import avif_98 from '../assets/Products/Trip-4/optimized/T4-800.avif';
import avif_99 from '../assets/Products/Trip-4/optimized/T4-1200.avif';
import webp_100 from '../assets/Products/Trip-4/optimized/T4-400.webp';
import webp_101 from '../assets/Products/Trip-4/optimized/T4-800.webp';
import webp_102 from '../assets/Products/Trip-4/optimized/T4-1200.webp';
import fb_103 from '../assets/Products/Trip-4/optimized/T4-400.jpg';
import fb_104 from '../assets/Products/Trip-4/optimized/T4-800.jpg';
import fb_105 from '../assets/Products/Trip-4/optimized/T4-1200.jpg';
import orig_106 from '../assets/Products/Trip-4/T44.jpg';
import avif_107 from '../assets/Products/Trip-4/optimized/T44-400.avif';
import avif_108 from '../assets/Products/Trip-4/optimized/T44-800.avif';
import webp_109 from '../assets/Products/Trip-4/optimized/T44-400.webp';
import webp_110 from '../assets/Products/Trip-4/optimized/T44-800.webp';
import fb_111 from '../assets/Products/Trip-4/optimized/T44-400.jpg';
import fb_112 from '../assets/Products/Trip-4/optimized/T44-800.jpg';
import orig_113 from '../assets/Products/Trip-4/T444.jpg';
import avif_114 from '../assets/Products/Trip-4/optimized/T444-400.avif';
import avif_115 from '../assets/Products/Trip-4/optimized/T444-800.avif';
import avif_116 from '../assets/Products/Trip-4/optimized/T444-1200.avif';
import webp_117 from '../assets/Products/Trip-4/optimized/T444-400.webp';
import webp_118 from '../assets/Products/Trip-4/optimized/T444-800.webp';
import webp_119 from '../assets/Products/Trip-4/optimized/T444-1200.webp';
import fb_120 from '../assets/Products/Trip-4/optimized/T444-400.jpg';
import fb_121 from '../assets/Products/Trip-4/optimized/T444-800.jpg';
import fb_122 from '../assets/Products/Trip-4/optimized/T444-1200.jpg';
import orig_123 from '../assets/Products/Trip-4/T4444.jpg';
import avif_124 from '../assets/Products/Trip-4/optimized/T4444-400.avif';
import avif_125 from '../assets/Products/Trip-4/optimized/T4444-800.avif';
import webp_126 from '../assets/Products/Trip-4/optimized/T4444-400.webp';
import webp_127 from '../assets/Products/Trip-4/optimized/T4444-800.webp';
import fb_128 from '../assets/Products/Trip-4/optimized/T4444-400.jpg';
import fb_129 from '../assets/Products/Trip-4/optimized/T4444-800.jpg';
import orig_130 from '../assets/Products/Trip-4/T44444.jpg';
import avif_131 from '../assets/Products/Trip-4/optimized/T44444-400.avif';
import avif_132 from '../assets/Products/Trip-4/optimized/T44444-800.avif';
import avif_133 from '../assets/Products/Trip-4/optimized/T44444-1200.avif';
import webp_134 from '../assets/Products/Trip-4/optimized/T44444-400.webp';
import webp_135 from '../assets/Products/Trip-4/optimized/T44444-800.webp';
import webp_136 from '../assets/Products/Trip-4/optimized/T44444-1200.webp';
import fb_137 from '../assets/Products/Trip-4/optimized/T44444-400.jpg';
import fb_138 from '../assets/Products/Trip-4/optimized/T44444-800.jpg';
import fb_139 from '../assets/Products/Trip-4/optimized/T44444-1200.jpg';
import orig_140 from '../assets/Products/Trip-5/T5.jpg';
import avif_141 from '../assets/Products/Trip-5/optimized/T5-400.avif';
import avif_142 from '../assets/Products/Trip-5/optimized/T5-800.avif';
import webp_143 from '../assets/Products/Trip-5/optimized/T5-400.webp';
import webp_144 from '../assets/Products/Trip-5/optimized/T5-800.webp';
import fb_145 from '../assets/Products/Trip-5/optimized/T5-400.jpg';
import fb_146 from '../assets/Products/Trip-5/optimized/T5-800.jpg';
import orig_147 from '../assets/Products/Trip-5/T55.jpg';
import avif_148 from '../assets/Products/Trip-5/optimized/T55-400.avif';
import avif_149 from '../assets/Products/Trip-5/optimized/T55-800.avif';
import avif_150 from '../assets/Products/Trip-5/optimized/T55-1200.avif';
import webp_151 from '../assets/Products/Trip-5/optimized/T55-400.webp';
import webp_152 from '../assets/Products/Trip-5/optimized/T55-800.webp';
import webp_153 from '../assets/Products/Trip-5/optimized/T55-1200.webp';
import fb_154 from '../assets/Products/Trip-5/optimized/T55-400.jpg';
import fb_155 from '../assets/Products/Trip-5/optimized/T55-800.jpg';
import fb_156 from '../assets/Products/Trip-5/optimized/T55-1200.jpg';
import orig_157 from '../assets/Products/Trip-5/T555.jpg';
import avif_158 from '../assets/Products/Trip-5/optimized/T555-400.avif';
import webp_159 from '../assets/Products/Trip-5/optimized/T555-400.webp';
import fb_160 from '../assets/Products/Trip-5/optimized/T555-400.jpg';
import orig_161 from '../assets/Products/Trip-5/T5555.jpg';
import avif_162 from '../assets/Products/Trip-5/optimized/T5555-400.avif';
import avif_163 from '../assets/Products/Trip-5/optimized/T5555-800.avif';
import webp_164 from '../assets/Products/Trip-5/optimized/T5555-400.webp';
import webp_165 from '../assets/Products/Trip-5/optimized/T5555-800.webp';
import fb_166 from '../assets/Products/Trip-5/optimized/T5555-400.jpg';
import fb_167 from '../assets/Products/Trip-5/optimized/T5555-800.jpg';
import orig_168 from '../assets/Products/Trip-5/T55555.jpg';
import avif_169 from '../assets/Products/Trip-5/optimized/T55555-400.avif';
import avif_170 from '../assets/Products/Trip-5/optimized/T55555-800.avif';
import avif_171 from '../assets/Products/Trip-5/optimized/T55555-1200.avif';
import webp_172 from '../assets/Products/Trip-5/optimized/T55555-400.webp';
import webp_173 from '../assets/Products/Trip-5/optimized/T55555-800.webp';
import webp_174 from '../assets/Products/Trip-5/optimized/T55555-1200.webp';
import fb_175 from '../assets/Products/Trip-5/optimized/T55555-400.jpg';
import fb_176 from '../assets/Products/Trip-5/optimized/T55555-800.jpg';
import fb_177 from '../assets/Products/Trip-5/optimized/T55555-1200.jpg';
import orig_178 from '../assets/Products/Trip-Sahara/T6.jpg';
import avif_179 from '../assets/Products/Trip-Sahara/optimized/T6-400.avif';
import webp_180 from '../assets/Products/Trip-Sahara/optimized/T6-400.webp';
import fb_181 from '../assets/Products/Trip-Sahara/optimized/T6-400.jpg';
import orig_182 from '../assets/Products/Trip-Sahara/T66.jpg';
import avif_183 from '../assets/Products/Trip-Sahara/optimized/T66-400.avif';
import avif_184 from '../assets/Products/Trip-Sahara/optimized/T66-800.avif';
import webp_185 from '../assets/Products/Trip-Sahara/optimized/T66-400.webp';
import webp_186 from '../assets/Products/Trip-Sahara/optimized/T66-800.webp';
import fb_187 from '../assets/Products/Trip-Sahara/optimized/T66-400.jpg';
import fb_188 from '../assets/Products/Trip-Sahara/optimized/T66-800.jpg';
import orig_189 from '../assets/Products/Trip-Sahara/T666.jpg';
import avif_190 from '../assets/Products/Trip-Sahara/optimized/T666-400.avif';
import avif_191 from '../assets/Products/Trip-Sahara/optimized/T666-800.avif';
import avif_192 from '../assets/Products/Trip-Sahara/optimized/T666-1200.avif';
import webp_193 from '../assets/Products/Trip-Sahara/optimized/T666-400.webp';
import webp_194 from '../assets/Products/Trip-Sahara/optimized/T666-800.webp';
import webp_195 from '../assets/Products/Trip-Sahara/optimized/T666-1200.webp';
import fb_196 from '../assets/Products/Trip-Sahara/optimized/T666-400.jpg';
import fb_197 from '../assets/Products/Trip-Sahara/optimized/T666-800.jpg';
import fb_198 from '../assets/Products/Trip-Sahara/optimized/T666-1200.jpg';
import orig_199 from '../assets/Products/Trip-Sahara/T6666.webp';
import avif_200 from '../assets/Products/Trip-Sahara/optimized/T6666-400.avif';
import avif_201 from '../assets/Products/Trip-Sahara/optimized/T6666-800.avif';
import avif_202 from '../assets/Products/Trip-Sahara/optimized/T6666-1200.avif';
import webp_203 from '../assets/Products/Trip-Sahara/optimized/T6666-400.webp';
import webp_204 from '../assets/Products/Trip-Sahara/optimized/T6666-800.webp';
import webp_205 from '../assets/Products/Trip-Sahara/optimized/T6666-1200.webp';
import fb_206 from '../assets/Products/Trip-Sahara/optimized/T6666-400.webp';
import fb_207 from '../assets/Products/Trip-Sahara/optimized/T6666-800.webp';
import fb_208 from '../assets/Products/Trip-Sahara/optimized/T6666-1200.webp';
import orig_209 from '../assets/Products/Trip-Sahara/T66666.jpg';
import avif_210 from '../assets/Products/Trip-Sahara/optimized/T66666-400.avif';
import avif_211 from '../assets/Products/Trip-Sahara/optimized/T66666-800.avif';
import avif_212 from '../assets/Products/Trip-Sahara/optimized/T66666-1200.avif';
import webp_213 from '../assets/Products/Trip-Sahara/optimized/T66666-400.webp';
import webp_214 from '../assets/Products/Trip-Sahara/optimized/T66666-800.webp';
import webp_215 from '../assets/Products/Trip-Sahara/optimized/T66666-1200.webp';
import fb_216 from '../assets/Products/Trip-Sahara/optimized/T66666-400.jpg';
import fb_217 from '../assets/Products/Trip-Sahara/optimized/T66666-800.jpg';
import fb_218 from '../assets/Products/Trip-Sahara/optimized/T66666-1200.jpg';

export interface OptimizedImageSource {
  avif: string;
  webp: string;
  fallback: string;
}

export const optimizedImagesMap = new Map<string | any, OptimizedImageSource>([
  [orig_0, {
    avif: [avif_1 + ' 400w'].join(', '),
    webp: [webp_2 + ' 400w'].join(', '),
    fallback: fb_3
  }],
  [orig_4, {
    avif: [avif_5 + ' 400w'].join(', '),
    webp: [webp_6 + ' 400w'].join(', '),
    fallback: fb_7
  }],
  [orig_8, {
    avif: [avif_9 + ' 400w', avif_10 + ' 800w', avif_11 + ' 1200w'].join(', '),
    webp: [webp_12 + ' 400w', webp_13 + ' 800w', webp_14 + ' 1200w'].join(', '),
    fallback: fb_16
  }],
  [orig_18, {
    avif: [avif_19 + ' 400w'].join(', '),
    webp: [webp_20 + ' 400w'].join(', '),
    fallback: fb_21
  }],
  [orig_22, {
    avif: [avif_23 + ' 400w', avif_24 + ' 800w'].join(', '),
    webp: [webp_25 + ' 400w', webp_26 + ' 800w'].join(', '),
    fallback: fb_28
  }],
  [orig_29, {
    avif: [avif_30 + ' 400w', avif_31 + ' 800w', avif_32 + ' 1200w'].join(', '),
    webp: [webp_33 + ' 400w', webp_34 + ' 800w', webp_35 + ' 1200w'].join(', '),
    fallback: fb_37
  }],
  [orig_39, {
    avif: [avif_40 + ' 400w', avif_41 + ' 800w'].join(', '),
    webp: [webp_42 + ' 400w', webp_43 + ' 800w'].join(', '),
    fallback: fb_45
  }],
  [orig_46, {
    avif: [avif_47 + ' 400w'].join(', '),
    webp: [webp_48 + ' 400w'].join(', '),
    fallback: fb_49
  }],
  [orig_50, {
    avif: [avif_51 + ' 259w'].join(', '),
    webp: [webp_52 + ' 259w'].join(', '),
    fallback: fb_53
  }],
  [orig_54, {
    avif: [avif_55 + ' 400w', avif_56 + ' 800w', avif_57 + ' 1200w'].join(', '),
    webp: [webp_58 + ' 400w', webp_59 + ' 800w', webp_60 + ' 1200w'].join(', '),
    fallback: fb_62
  }],
  [orig_64, {
    avif: [avif_65 + ' 400w', avif_66 + ' 800w', avif_67 + ' 1200w'].join(', '),
    webp: [webp_68 + ' 400w', webp_69 + ' 800w', webp_70 + ' 1200w'].join(', '),
    fallback: fb_72
  }],
  [orig_74, {
    avif: [avif_75 + ' 400w', avif_76 + ' 800w'].join(', '),
    webp: [webp_77 + ' 400w', webp_78 + ' 800w'].join(', '),
    fallback: fb_80
  }],
  [orig_81, {
    avif: [avif_82 + ' 259w'].join(', '),
    webp: [webp_83 + ' 259w'].join(', '),
    fallback: fb_84
  }],
  [orig_85, {
    avif: [avif_86 + ' 225w'].join(', '),
    webp: [webp_87 + ' 225w'].join(', '),
    fallback: fb_88
  }],
  [orig_89, {
    avif: [avif_90 + ' 400w', avif_91 + ' 800w'].join(', '),
    webp: [webp_92 + ' 400w', webp_93 + ' 800w'].join(', '),
    fallback: fb_95
  }],
  [orig_96, {
    avif: [avif_97 + ' 400w', avif_98 + ' 800w', avif_99 + ' 1200w'].join(', '),
    webp: [webp_100 + ' 400w', webp_101 + ' 800w', webp_102 + ' 1200w'].join(', '),
    fallback: fb_104
  }],
  [orig_106, {
    avif: [avif_107 + ' 400w', avif_108 + ' 800w'].join(', '),
    webp: [webp_109 + ' 400w', webp_110 + ' 800w'].join(', '),
    fallback: fb_112
  }],
  [orig_113, {
    avif: [avif_114 + ' 400w', avif_115 + ' 800w', avif_116 + ' 1200w'].join(', '),
    webp: [webp_117 + ' 400w', webp_118 + ' 800w', webp_119 + ' 1200w'].join(', '),
    fallback: fb_121
  }],
  [orig_123, {
    avif: [avif_124 + ' 400w', avif_125 + ' 800w'].join(', '),
    webp: [webp_126 + ' 400w', webp_127 + ' 800w'].join(', '),
    fallback: fb_129
  }],
  [orig_130, {
    avif: [avif_131 + ' 400w', avif_132 + ' 800w', avif_133 + ' 1200w'].join(', '),
    webp: [webp_134 + ' 400w', webp_135 + ' 800w', webp_136 + ' 1200w'].join(', '),
    fallback: fb_138
  }],
  [orig_140, {
    avif: [avif_141 + ' 400w', avif_142 + ' 800w'].join(', '),
    webp: [webp_143 + ' 400w', webp_144 + ' 800w'].join(', '),
    fallback: fb_146
  }],
  [orig_147, {
    avif: [avif_148 + ' 400w', avif_149 + ' 800w', avif_150 + ' 1200w'].join(', '),
    webp: [webp_151 + ' 400w', webp_152 + ' 800w', webp_153 + ' 1200w'].join(', '),
    fallback: fb_155
  }],
  [orig_157, {
    avif: [avif_158 + ' 400w'].join(', '),
    webp: [webp_159 + ' 400w'].join(', '),
    fallback: fb_160
  }],
  [orig_161, {
    avif: [avif_162 + ' 400w', avif_163 + ' 800w'].join(', '),
    webp: [webp_164 + ' 400w', webp_165 + ' 800w'].join(', '),
    fallback: fb_167
  }],
  [orig_168, {
    avif: [avif_169 + ' 400w', avif_170 + ' 800w', avif_171 + ' 1200w'].join(', '),
    webp: [webp_172 + ' 400w', webp_173 + ' 800w', webp_174 + ' 1200w'].join(', '),
    fallback: fb_176
  }],
  [orig_178, {
    avif: [avif_179 + ' 400w'].join(', '),
    webp: [webp_180 + ' 400w'].join(', '),
    fallback: fb_181
  }],
  [orig_182, {
    avif: [avif_183 + ' 400w', avif_184 + ' 800w'].join(', '),
    webp: [webp_185 + ' 400w', webp_186 + ' 800w'].join(', '),
    fallback: fb_188
  }],
  [orig_189, {
    avif: [avif_190 + ' 400w', avif_191 + ' 800w', avif_192 + ' 1200w'].join(', '),
    webp: [webp_193 + ' 400w', webp_194 + ' 800w', webp_195 + ' 1200w'].join(', '),
    fallback: fb_197
  }],
  [orig_199, {
    avif: [avif_200 + ' 400w', avif_201 + ' 800w', avif_202 + ' 1200w'].join(', '),
    webp: [webp_203 + ' 400w', webp_204 + ' 800w', webp_205 + ' 1200w'].join(', '),
    fallback: fb_207
  }],
  [orig_209, {
    avif: [avif_210 + ' 400w', avif_211 + ' 800w', avif_212 + ' 1200w'].join(', '),
    webp: [webp_213 + ' 400w', webp_214 + ' 800w', webp_215 + ' 1200w'].join(', '),
    fallback: fb_217
  }],
  ['/images/insta icon - igv.jpeg', {
    avif: [`/images/optimized/insta icon - igv-400.avif 400w`, `/images/optimized/insta icon - igv-800.avif 800w`].join(', '),
    webp: [`/images/optimized/insta icon - igv-400.webp 400w`, `/images/optimized/insta icon - igv-800.webp 800w`].join(', '),
    fallback: '/images/optimized/insta icon - igv-800.jpeg'
  }],
  ['/images/insta icon - traveland.jpeg', {
    avif: [`/images/optimized/insta icon - traveland-400.avif 400w`, `/images/optimized/insta icon - traveland-800.avif 800w`].join(', '),
    webp: [`/images/optimized/insta icon - traveland-400.webp 400w`, `/images/optimized/insta icon - traveland-800.webp 800w`].join(', '),
    fallback: '/images/optimized/insta icon - traveland-800.jpeg'
  }],
  ['/images/Post - igv.jpg', {
    avif: [`/images/optimized/Post - igv-400.avif 400w`, `/images/optimized/Post - igv-800.avif 800w`].join(', '),
    webp: [`/images/optimized/Post - igv-400.webp 400w`, `/images/optimized/Post - igv-800.webp 800w`].join(', '),
    fallback: '/images/optimized/Post - igv-800.jpg'
  }],
  ['/images/Post - traveland.png', {
    avif: [`/images/optimized/Post - traveland-400.avif 400w`, `/images/optimized/Post - traveland-800.avif 800w`].join(', '),
    webp: [`/images/optimized/Post - traveland-400.webp 400w`, `/images/optimized/Post - traveland-800.webp 800w`].join(', '),
    fallback: '/images/optimized/Post - traveland-800.png'
  }]
]);
const _unused = [fb_15, fb_17, fb_27, fb_36, fb_38, fb_44, fb_61, fb_63, fb_71, fb_73, fb_79, fb_94, fb_103, fb_105, fb_111, fb_120, fb_122, fb_128, fb_137, fb_139, fb_145, fb_154, fb_156, fb_166, fb_175, fb_177, fb_187, fb_196, fb_198, fb_206, fb_208, fb_216, fb_218];
